language: ruby
rvm:
- 2.4.0
env:
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:create db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
before_script:
- mysql -e 'create database mydb_test'
bundler_args: "--binstubs=./bundler_stubs"
deploy:
  provider: heroku
  api_key: c0c284af-d2bd-49ba-bc4a-98a2d4ae0e64
  app: tranquil-thicket-51917
  on:
    repo: afishcalledrob/make_my_day_app
