language: ruby

rvm:
  - 2.4.0



before_script:
  -bundle
  -bin/rails db:create
  -bin/rails db:migrate
  -bundle exec rspec spec

script:

deploy:
  provider: heroku
  api_key: ...
  app: tranquil-thicket-51917
  on:
    repo: afishcalledrob/make_my_day_app
